from tests.alembic_custom_type_migration_support import run_custom_type_migration


def test_autogenerated_custom_type_revision_runs_on_sqlite(tmp_path):
    database_path = tmp_path / "custom-types.sqlite3"

    revision_source = run_custom_type_migration(
        tmp_path,
        database_url=f"sqlite:///{database_path}",
        db_type="sqlite",
    )

    assert "import repom.custom_types.UTCDateTime" in revision_source
    assert "import repom.custom_types.ListJSON" in revision_source
