from textwrap import dedent, indent
from types import SimpleNamespace

import sqlalchemy as sa
from alembic.autogenerate import produce_migrations, render_python_code
from alembic.migration import MigrationContext
from sqlalchemy import Column, Integer, MetaData, Table, create_engine

from repom.alembic import render_repom_type
from repom.custom_types.AutoDateTime import AutoDateTime
from repom.custom_types.CustomJSON import CustomJSON
from repom.custom_types.ListJSON import ListJSON
from repom.custom_types.UTCDateTime import UTCDateTime


def test_autogenerated_repom_custom_types_include_imports_and_execute():
    metadata = MetaData()
    Table(
        "alembic_custom_type_render",
        metadata,
        Column("id", Integer, primary_key=True),
        Column("utc_at", UTCDateTime(), nullable=True),
        Column("auto_at", AutoDateTime(), nullable=True),
        Column("tags", ListJSON(), nullable=True),
        Column("payload", CustomJSON(), nullable=True),
    )
    imports = set()
    autogen_context = SimpleNamespace(imports=imports)
    for column in metadata.tables["alembic_custom_type_render"].columns:
        rendered_type = render_repom_type("type", column.type, autogen_context)
        assert rendered_type is False

    with create_engine("sqlite://").connect() as connection:
        migration_context = MigrationContext.configure(connection)
        migration = produce_migrations(migration_context, metadata)
        rendered = render_python_code(
            migration.upgrade_ops,
            migration_context=migration_context,
            imports=imports,
            render_item=render_repom_type,
        )

    expected_imports = {
        "import repom.custom_types.UTCDateTime",
        "import repom.custom_types.AutoDateTime",
        "import repom.custom_types.ListJSON",
        "import repom.custom_types.CustomJSON",
    }
    assert imports == expected_imports
    assert "repom.custom_types.UTCDateTime.UTCDateTime(timezone=True)" in rendered
    assert "repom.custom_types.AutoDateTime.AutoDateTime(timezone=True)" in rendered
    assert "repom.custom_types.ListJSON.ListJSON()" in rendered
    assert "repom.custom_types.CustomJSON.CustomJSON()" in rendered

    namespace = {
        "sa": sa,
        "op": SimpleNamespace(create_table=lambda *args, **kwargs: None),
    }
    exec("\n".join(sorted(imports)), namespace)
    exec(f"def upgrade():\n{indent(dedent(rendered), '    ')}\n", namespace)
    namespace["upgrade"]()
