"""comment

Revision ID: dbdcc59b0b68
Revises: 
Create Date: 2026-02-24 19:20:45.586402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import repom


# revision identifiers, used by Alembic.
revision: str = 'dbdcc59b0b68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samples',
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('done_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', repom.custom_types.AutoDateTime.AutoDateTime(), nullable=False),
    sa.Column('updated_at', repom.custom_types.AutoDateTime.AutoDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('created_at', repom.custom_types.AutoDateTime.AutoDateTime(), nullable=False),
    sa.Column('updated_at', repom.custom_types.AutoDateTime.AutoDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'session_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_sessions')
    op.drop_table('samples')
    # ### end Alembic commands ###
