"""Redis container management commands.

Console scripts:
    uv run redis_generate
    uv run redis_start
    uv run redis_stop
    uv run redis_remove
    uv run redis_rotate_password
"""

from __future__ import annotations

import subprocess

from repom.config import config
from repom.redis.credentials import (
    RedisCredentialRotationPlan,
    build_redis_ping_command,
    rotate_redis_password,
)
from basekit.docker_compose import (
    DockerComposeGenerator,
    DockerService,
    DockerVolume,
)
from basekit.docker_manager import DockerCommandExecutor, DockerManager
from repom.docker_service import (
    ensure_running as ensure_container_service_running,
    remove_service,
    start_service,
    stop_service,
)

COMPOSE_FILENAME = "docker-compose.generated.yml"


class RedisManager(DockerManager):
    """Container manager for the repom Redis service."""

    SERVICE_NAME = "redis"
    INIT_SUBDIR = "redis_init"
    GENERATE_COMMAND = "redis_generate"

    def __init__(self):
        super().__init__(data_path=config.data_path)
        self.config = config

    def get_container_name(self) -> str:
        """Return the configured Redis container name."""

        return self.config.redis.container.get_container_name()

    def wait_for_service(self, max_retries: int = 30) -> None:
        """Wait until redis-cli ping succeeds inside the Redis container."""

        container_name = self.get_container_name()
        password = self.config.redis.password

        def check_redis_ready():
            try:
                result = subprocess.run(
                    build_redis_ping_command(
                        container_name=container_name,
                        password=password,
                    ),
                    capture_output=True,
                    text=True,
                    timeout=2,
                    check=False,
                )
                return result.returncode == 0 and "PONG" in result.stdout
            except Exception:
                return False

        DockerCommandExecutor.wait_for_readiness(
            check_redis_ready,
            max_retries=max_retries,
            service_name="Redis",
        )

    def print_connection_info(self) -> None:
        """Print local Redis connection details."""

        print()
        print(" Redis Connection:")
        print("  Host: localhost")
        print(f"  Port: {self.config.redis.port}")
        if self.config.redis.password:
            print("  Auth: enabled")
            print(f"  CLI: REDISCLI_AUTH=*** redis-cli -p {self.config.redis.port}")
        else:
            print("  Auth: disabled")
            print(f"  CLI: redis-cli -p {self.config.redis.port}")
        print()


def _format_redis_conf_value(value: str) -> str:
    """Format a Redis config string value."""

    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def generate_redis_conf(password: str | None = None) -> str:
    """Generate redis.conf content from the active config."""

    redis_password = config.redis.password if password is None else password
    auth_lines = []
    if redis_password:
        auth_lines.extend(
            [
                "# Authentication",
                f"requirepass {_format_redis_conf_value(redis_password)}",
                "",
            ]
        )

    return """# Redis Configuration (auto-generated by repom)
#
# Do not edit manually - modify config in repom/config.py instead

{auth_section}\
# Database
databases 16

# Persistence
appendonly yes
appendfsync everysec

# Snapshots
save 900 1
save 300 10
save 60 10000

# Memory
maxmemory 256mb
maxmemory-policy allkeys-lru

# Logging
loglevel notice
""".format(auth_section="\n".join(auth_lines))


def generate_docker_compose() -> DockerComposeGenerator:
    """Generate a compose model for Redis."""

    manager = RedisManager()
    redis_port = config.redis.port
    redis_password = config.redis.password
    container_name = config.redis.container.get_container_name()
    volume_name = config.redis.container.get_volume_name()
    image = config.redis.container.image
    init_dir = manager.get_init_dir()

    environment = {"REDIS_PASSWORD": redis_password} if redis_password else {}
    healthcheck_test = '["CMD", "redis-cli", "ping"]'
    if redis_password:
        healthcheck_test = '["CMD-SHELL", "redis-cli -a \\"$$REDIS_PASSWORD\\" ping"]'

    redis_service = DockerService(
        name="redis",
        image=image,
        container_name=container_name,
        environment=environment,
        ports=[f"{redis_port}:6379"],
        volumes=[
            f"{volume_name}:/data",
            f"{init_dir.absolute()}/redis.conf:/usr/local/etc/redis/redis.conf",
        ],
        command="redis-server /usr/local/etc/redis/redis.conf",
        healthcheck={
            "test": healthcheck_test,
            "interval": "5s",
            "timeout": "5s",
            "retries": 5,
        },
    )

    generator = DockerComposeGenerator()
    generator.add_service(redis_service)
    generator.add_volume(DockerVolume(name=volume_name))

    return generator


def generate():
    """Write Redis compose and redis.conf files."""

    manager = RedisManager()
    init_dir = manager.get_init_dir()
    redis_conf = generate_redis_conf()
    (init_dir / "redis.conf").write_text(redis_conf, encoding="utf-8")

    generator = generate_docker_compose()
    compose_dir = manager.get_compose_dir()
    output_path = compose_dir / COMPOSE_FILENAME
    generator.write_to_file(output_path)

    print(f"Generated: {output_path}")
    print(f"   Config: {init_dir / 'redis.conf'}")
    print("\n Redis Service:")
    print(f"   Container: {config.redis.container.get_container_name()}")
    print(f"   Port: {config.redis.port}")
    print(f"   Volume: {config.redis.container.get_volume_name()}")
    print(f"   Auth: {'enabled' if config.redis.password else 'disabled'}")


def start():
    """Generate files and start Redis."""

    start_service(RedisManager, generate)


def stop():
    """Stop Redis."""

    stop_service(RedisManager)


def ensure_running(*, timeout_seconds: int = 30) -> None:
    """Ensure Redis is running for application lifespan hooks.

    The compose files are generated and the Redis container is started when it
    is not already running.

    Args:
        timeout_seconds: Number of seconds to wait for readiness.

    Raises:
        RuntimeError: The container runtime is unavailable or Redis fails to start.
    """

    ensure_container_service_running(
        RedisManager,
        {"redis": config.redis.container.get_container_name()},
        generate,
        "Redis",
        timeout_seconds,
    )


def remove():
    """Remove Redis containers and volumes."""

    remove_service(RedisManager)


def rotate_password(
    new_password: str | None = None,
    *,
    old_password: str | None = None,
    dry_run: bool = True,
):
    """Apply a new Redis password to the running instance and persisted config."""

    password = new_password or config.redis.password
    if not password:
        raise ValueError(
            "new_password or config.redis.password is required for Redis rotation"
        )

    result = rotate_redis_password(
        plan=RedisCredentialRotationPlan.from_config(
            old_password=old_password,
            new_password=password,
        ),
        dry_run=dry_run,
    )
    if not dry_run:
        config.redis.password = password
        generate()
    for line in (result.masked_command, result.masked_input.strip()):
        print(line)
    return result


def main_rotate_password():
    """Console entry point for Redis password rotation."""

    import argparse

    parser = argparse.ArgumentParser(
        description="Rotate the password for a running repom Redis container."
    )
    parser.add_argument("--new-password", default=None)
    parser.add_argument("--old-password", default=None)
    parser.add_argument(
        "--execute",
        action="store_true",
        help="Execute the rotation. Without this flag, only a dry-run is printed.",
    )
    args = parser.parse_args()
    rotate_password(
        new_password=args.new_password,
        old_password=args.old_password,
        dry_run=not args.execute,
    )
