"""Redis Docker 環境管理スクリプト

使用方法:
    uv run redis_generate   # docker-compose.yml を生成
    uv run redis_start      # Redis を起動
    uv run redis_stop       # Redis を停止
    uv run redis_remove     # Redis を削除
"""

import subprocess
import sys

from repom.config import config
from repom._.docker_compose import DockerComposeGenerator, DockerService, DockerVolume
from repom._ import docker_manager as dm


def get_compose_dir():
    """docker-compose.yml の保存先ディレクトリを取得

    Returns:
        config.data_path/redis/ ディレクトリ（分離プロジェクト構造）
    """
    return RedisManager().get_compose_dir()


class RedisManager(dm.DockerManager):
    """Redis コンテナの管理（Docker Manager 基盤を使用）

    docker-compose による start/stop/remove は DockerManager 基盤クラスから継承
    """

    SERVICE_NAME = "redis"
    INIT_SUBDIR = "redis_init"
    GENERATE_COMMAND = "redis_generate"

    def __init__(self):
        self.config = config

    def get_container_name(self) -> str:
        """Redis コンテナ名を返す"""
        return self.config.redis.container.get_container_name()

    def wait_for_service(self, max_retries: int = 30) -> None:
        """Redis の起動を待機（redis-cli ping による確認）"""
        container_name = self.get_container_name()

        def check_redis_ready():
            try:
                result = subprocess.run(
                    ["docker", "exec", container_name, "redis-cli", "ping"],
                    capture_output=True,
                    text=True,
                    timeout=2,
                    check=False
                )
                return result.returncode == 0 and "PONG" in result.stdout
            except Exception:
                return False

        dm.DockerCommandExecutor.wait_for_readiness(
            check_redis_ready,
            max_retries=max_retries,
            service_name="Redis"
        )

    def print_connection_info(self) -> None:
        """Redis 接続情報を表示"""
        print()
        print("📦 Redis Connection:")
        print(f"  Host: localhost")
        print(f"  Port: {self.config.redis.port}")
        print(f"  CLI: redis-cli -p {self.config.redis.port}")
        print()


def get_init_dir():
    """Redis 初期化ファイルのディレクトリを取得

    Returns:
        config.data_path/redis_init/ ディレクトリ
    """
    return RedisManager().get_init_dir()


def generate_redis_conf() -> str:
    """Redis 設定ファイルを生成

    基本的な redis.conf を動的に生成する
    """
    return """# Redis Configuration (auto-generated by repom)
# 
# Do not edit manually - modify config in repom/config.py instead

# Database
databases 16

# Persistence
appendonly yes
appendfsync everysec

# Snapshots
save 900 1
save 300 10
save 60 10000

# Memory
maxmemory 256mb
maxmemory-policy allkeys-lru

# Logging
loglevel notice
"""


def generate_docker_compose() -> DockerComposeGenerator:
    """config から docker-compose.yml 生成器を作成"""
    redis_port = config.redis.port
    container_name = config.redis.container.get_container_name()
    volume_name = config.redis.container.get_volume_name()
    image = config.redis.container.image

    # init ファイルのパスを取得
    init_dir = get_init_dir()

    # Redis サービスを定義
    redis_service = DockerService(
        name="redis",
        image=image,
        container_name=container_name,
        ports=[f"{redis_port}:6379"],
        volumes=[
            f"{volume_name}:/data",
            f"{init_dir.absolute()}/redis.conf:/usr/local/etc/redis/redis.conf",
        ],
        command="redis-server /usr/local/etc/redis/redis.conf",
        healthcheck={
            "test": '["CMD", "redis-cli", "ping"]',
            "interval": "5s",
            "timeout": "5s",
            "retries": 5,
        }
    )

    # Docker Volume を定義
    data_volume = DockerVolume(name=volume_name)

    # 生成器を作成
    generator = DockerComposeGenerator()
    generator.add_service(redis_service)
    generator.add_volume(data_volume)

    return generator


def generate():
    """docker-compose.yml と Redis 設定を生成（コマンドから呼び出し可能）"""
    # Redis 設定ファイルを生成
    init_dir = get_init_dir()
    redis_conf = generate_redis_conf()
    (init_dir / "redis.conf").write_text(redis_conf, encoding="utf-8")

    # docker-compose.yml を生成
    generator = generate_docker_compose()
    compose_dir = get_compose_dir()
    output_path = compose_dir / "docker-compose.generated.yml"
    generator.write_to_file(output_path)

    print(f"✅ Generated: {output_path}")
    print(f"   Config: {init_dir / 'redis.conf'}")
    print(f"\n📦 Redis Service:")
    print(f"   Container: {config.redis.container.get_container_name()}")
    print(f"   Port: {config.redis.port}")
    print(f"   Volume: {config.redis.container.get_volume_name()}")


def start():
    """Redis を起動"""
    # docker-compose.yml を生成
    generate()

    manager = RedisManager()

    try:
        manager.start()
        manager.print_connection_info()
    except TimeoutError as e:
        print(f"❌ {e}")
        print(f"Check logs: docker logs repom_redis")
        sys.exit(1)


def stop():
    """Redis を停止（コンテナ停止のみ、削除はしない）"""
    manager = RedisManager()

    try:
        manager.stop()
    except SystemExit:
        raise


def remove():
    """Redis コンテナとボリュームを削除（完全リセット）"""
    manager = RedisManager()

    try:
        manager.remove()
    except SystemExit:
        raise


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python manage.py [generate|start|stop|remove]")
        sys.exit(1)

    command = sys.argv[1]
    if command == "generate":
        generate()
    elif command == "start":
        start()
    elif command == "stop":
        stop()
    elif command == "remove":
        remove()
    else:
        print(f"Unknown command: {command}")
        print("Usage: python manage.py [generate|start|stop|remove]")
        sys.exit(1)
