"""Alembic render hooks for repom-specific SQLAlchemy types."""


def render_repom_type(type_, obj, autogen_context):
    """Import repom custom types referenced by autogenerated revisions."""
    if type_ == "type" and type(obj).__module__.startswith("repom.custom_types"):
        module_path = type(obj).__module__
        autogen_context.imports.add(f"import {module_path}")
    return False
